### ISSUE TITLE
backpopulate the project label on a namesapce if that namespace is used in launching an app

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#1143]
As the title says. This will make that namespace show up as a project when you do `acorn projects`

**Comment by flobaader** [comment]
This would be nice! With the GitLab Kubernetes Integration a Namespace is automatically created for that environment, that can directly be used for the project namespace

**Comment by cjellick** [comment]
@ibuildthecloud i'm going to have someone do this for v0.6.0. Just let me know if you have any grander schemes for projects that would affect this

**Comment by sangee2004** [comment]
Tested with acorn version -  `v0.5.1-46-g1e0a96b+1e0a96be`

1. Create a namespace in kubectl - test1
2. Deployed app in the namespace using - `acorn run -j  test1 .` 
3. This resulted in `test1` becoming a project - label - `acorn.io/project=true` was added to `test1` namespace.
4. Able to list/use and delete this project.

**Comment by sangee2004** [comment]
Tested with acorn version `v0.5.1-49-gdc65d88+dc65d881`

1. Create a namespace and  deploy apps in the namespace using ` kubectl apply`
```
% cat  testns.yml 
apiVersion: v1
kind: Namespace
metadata:
  name: testy3

 % cat  test.yml  
apiVersion: api.acorn.io/v1
kind: App
metadata:
  name: test1
  namespace: testy3
spec:
  image: docker.io/sangeetha/myfirstacorn:v6.0.0

```

```
 % kubectl apply -f testns.yml -f test.yml
namespace/testy3 created
app.api.acorn.io/test1 created
```

`label - acorn.io/project=true` gets  added to `testy3` namespace.
We see `testy3` project being listed in project list view.
