### ISSUE TITLE
acorn pull image failed

### ISSUE THREAD

**Issue by eslizn** [acorn-io/acorn#1158]
create an app using acorn:
```bash
acorn run -n test ./
```
Acornfile:
```
containers: {
 default: {
  image: "nginx"
  ports: publish: "80/http"
  files: {
   // Simple index.html file
   "/usr/share/nginx/html/index.html": "<h1>My First Acorn!</h1>"
  }
 }
}
```
operation blocking，show apps：
```
NAME      IMAGE          HEALTHY   UP-TO-DATE   CREATED   ENDPOINTS                                MESSAGE
test      8125457ffc07   0/1       1            21m ago   http://<Pending Ingress> => default:80   [containers: default ImagePullBackOff: Back-off pulling image "127.0.0.1:30591/acorn/acorn@sha256:37ab22164e4ccd2b23d923c8939c55d7700da8657f7484fe5fcef4bb558e830b"]
```

acorn info:
```
---
client:
  cli:
    hubServers:
    - acorn.io
  version:
    commit: 7a4904c7d2d1077885ad6e2775550666b0a96905
    tag: v0.5.0
project:
  publicKeys:
  - keyID: ***
server:
  apiServerImage: ghcr.io/acorn-io/acorn:v0.5.0
  config:
    acornDNS: disabled
    acornDNSEndpoint: https://alpha-dns.acrn.io/v1
    autoUpgradeInterval: 5m
    builderPerProject: false
    clusterDomains:
    - .***
    defaultPublishMode: defined
    httpEndpointPattern: '{{.App}}.{{.ClusterDomain}}'
    ignoreUserLabelsAndAnnotations: false
    ingressClassName: traefik
    internalClusterDomain: svc.cluster.local
    internalRegistryPrefix: ""
    letsEncrypt: enabled
    letsEncryptEmail: ***
    letsEncryptTOSAgree: true
    podSecurityEnforceProfile: baseline
    publishBuilders: false
    recordBuilds: false
    setPodSecurityEnforceProfile: true
    useCustomCABundle: false
    workloadMemoryDefault: 0
    workloadMemoryMaximum: 0
  controllerImage: ghcr.io/acorn-io/acorn:v0.5.0
  dirty: false
  gitCommit: 7a4904c7d2d1077885ad6e2775550666b0a96905
  letsEncryptCertificate: enabled, pending (secrets "acorn-tls" not found)
  tag: v0.5.0
  userConfig:
    acornDNS: disabled
    acornDNSEndpoint: null
    autoUpgradeInterval: null
    builderPerProject: null
    clusterDomains:
    - .***
    defaultPublishMode: ""
    httpEndpointPattern: '{{.App}}.{{.ClusterDomain}}'
    ignoreUserLabelsAndAnnotations: null
    ingressClassName: traefik
    internalClusterDomain: ""
    internalRegistryPrefix: null
    letsEncrypt: enabled
    letsEncryptEmail: ***
    letsEncryptTOSAgree: true
    podSecurityEnforceProfile: ""
    publishBuilders: null
    recordBuilds: null
    setPodSecurityEnforceProfile: null
    useCustomCABundle: false
    workloadMemoryDefault: null
    workloadMemoryMaximum: null
  version: v0.5.0+7a4904c7
```
