### ISSUE TITLE
0 gets included in the "MEMORY RANGE" when clustercomputeclasses get created with `values` and no "min/max".

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1277]
Acorn version - v0.5.1-85-g787a9291+787a9291

Steps to reproduce the problem:
Created clustercomputeclasses  using the following yaml:
```
kind: ClusterComputeClassInstance
apiVersion: internal.admin.acorn.io/v1
default: true
metadata:
  name: cwc2
description: Large compute for linux on arm64
cpuScaler: 0.25
memory:
  default: 20G
  values:
  - 10G
  - 20G
  - 30G
tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value2"
    effect: "NoSchedule"
affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "tier"
            operator: "Equal"
            values:
            - "silver"
 ```
`MEMORY RANGE` include 0 "Memory Range". 
```
kubectl get clustercomputeclass
NAME   DEFAULT   MEMORY RANGE    MEMORT DEFAULT   DESCRIPTION
cwc1   *         10G-100G        20G              Large compute for linux on arm64
cwc2             0,10G,20G,30G   20G              Large compute for linux on arm64
root@sangeetest:~/computeclass# 
```

Expected Behavior:
`MEMORY RANGE`  should not include 0 "Memory Range". 

Note: This issue is also seen with projectcomputeclasses
