### ISSUE TITLE
Allowed to create computeclass with default  Memory value outside the memory range  

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1283]
acorn version v0.5.1-85-g787a9291+787a9291

Steps to reproduce the problem:

1.  Create computeclass with default memory that is not one of the values from the allowed list of values.

```
kind: ClusterComputeClass
apiVersion: admin.acorn.io/v1
default: false
metadata:
  name: cwc2
description: Large compute for linux on arm64
cpuScaler: 0.25
memory:
  default: 20G
  values:
  - 10M
  - 20M
  - 30M
tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value2"
    effect: "NoSchedule"
affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "tier"
            operator: "In"
            values:
            - "silver"
```

```
NAME      DEFAULT   MEMORY RANGE        MEMORT DEFAULT   DESCRIPTION
cwc2                0,10M,20G,20M,30M   20G              Large compute for linux on arm64
```

Expected behavior is for this to fail.
