### ISSUE TITLE
No validations done for toleration and affinity rules set for ComupteClass.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1305]
acorn version - acorn version v0.6.0-rc2+c6ffc99d

Steps to reproduce the problem:

1. Create a  projectcomputeclass/clustercomputeclass with following yaml which was invalid values :

```
kind: ClusterComputeClass
apiVersion: admin.acorn.io/v1
default: false
metadata:
  name: cwc2
description: Large compute for linux on arm64
cpuScaler: 0.25
memory:
  default: 30M
  values:
  - 10M
  - 20M
  - 30M
tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value2"
    effect: "NoScheduler"   ==>(Invalid)
  - key: "key1"
    operator: "Equal"
    value: "value2"
    effect: "NoExecute"
affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "tier"
            operator: "Equals"  ==>(Invalid)
            values:
            - "silver"
```
2. compute class gets created successfully.
3. App deployment with this computeclass fails with following error:

```
STATUS: ENDPOINTS[http://<Pending Ingress> => web1:80, http://<Pending Ingress> => web2:80, http://<Pending Ingress> => web3:80] HEALTHY[0] UPTODATE[0] [controller: failed to create myteste-76c71b61-400/web1 apps/v1, Kind=Deployment for acorn-controller p1/myteste: Deployment.apps "web1" is invalid: [spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].operator: Invalid value: "Equals": not a valid selector operator, spec.template.spec.tolerations[0].effect: Unsupported value: "NoScheduler": supported values: "NoSchedule", "PreferNoSchedule", "NoExecute"], failed to create myteste-76c71b61-400/web2 apps/v1, Kind=Deployment for acorn-controller p1/myteste: Deployment.apps "web2" is invalid: [spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].operator: Invalid value: "Equals": not a valid selector operator, spec.template.spec.tolerations[0].effect: Unsupported value: "NoScheduler": supported values: "NoSchedule", "PreferNoSchedule", "NoExecute"], failed to create myteste-76c71b61-400/web3 apps/v1, Kind=Deployment for acorn-controller p1/myteste: Deployment.apps "web3" is invalid: [spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].operator: Invalid value: "Equals": not a valid selector operator, spec.template.spec.tolerations[0].effect: Unsupported value: "NoScheduler": supported values: "NoSchedule", "PreferNoSchedule", "NoExecute"]]
```

Expected Behavior:

Ideally we should be abe to validate the syntax of toleration and affinity rules set in the compute class and error out at the time of creating the computeclass.
