### ISSUE TITLE
Incorrect GVK reported by kubectl for VolumeClasses

### ISSUE THREAD

**Issue by thedadams** [acorn-io/acorn#1355]
When using `kubectl get volumeclass -A -o yaml`, the GVK reported are incorrect. For example, on a fresh, default install of Acorn, running the given command will produce output with `ClusterVolumeClassInstance` in the `internal.admin.acorn.io` group.

These objects should have kind `VolumeClass` in the `api.acorn.io` group.

Thanks to @njhale for reporting this.

**Comment by sangee2004** [comment]
Tested with `acorn version v0.6.0-41-g7d82bde4+7d82bde4`

volumeClasses get reported with  `kind: VolumeClass` and `apiVersion: api.acorn.io/v1`

```
% kubectl get volumeclass -A -o yaml
apiVersion: v1
items:
- apiVersion: api.acorn.io/v1
  default: true
  description: Acorn-generated volume class representing the storage class local-path
  kind: VolumeClass
```
