### ISSUE TITLE
Containers that specify multiple published ports are only actually published on the first one listed

### ISSUE THREAD

**Issue by g-linville** [acorn-io/acorn#1402]
Found this bug while working with the current main branch.

Example Acornfile:
```cue
containers: {
  "nginx": {
    image: "nginx:latest"
    ports: publish: [
      "8080/http",
      "9090/http",
    ]
    files: {
      "/etc/nginx/conf.d/default.conf": """
      server {
          listen       8080;
          server_name  localhost;
          location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
          }
          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
              root   /usr/share/nginx/html;
          }
          rewrite /v2/.*$ /;
          rewrite /v2 /;
      }
      server {
          listen       9090;
          server_name  localhost;
          location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
          }
          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
              root   /usr/share/nginx/html;
          }
      }
      """
    }
  }
}
```

This is a single NGINX container that listens on ports 8080 and 9090. The Acornfile specifies that both of these ports should be published. When I run the app, only port 8080 gets published. This is the spec of the Ingress that was created:

```yaml
spec:
  ingressClassName: traefik
  rules:
  - host: nginx-nginx-publish-82c5d9f6.local.on-acorn.io
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 8080
        path: /
        pathType: Prefix
```

This is the only Ingress resource that was created for this app.
