### ISSUE TITLE
When app deployment is prevented because of not having matching annotation, error message complains about `.signatures.0.anyOf`

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1410]
acorn version v0.6.0-93-gd9de8c30+d9de8c30

Steps to reproduce the problem:
Create ImageAllowRules:
```
kind: ImageAllowRules
metadata:
  name: testrules-project
  namespace: testp1
signatures:
  rules:
    - signedBy:
        anyOf:
          - |
            -----BEGIN PUBLIC KEY-----
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEn3TS2G8lKMA2B6CT9mWZ3H6Z4k/h
            5RvYIFIPNvExwsV40B9xi3v2jBF2ODSINhPxHJOAs+eHZW3AitIwthqOsQ==
            -----END PUBLIC KEY-----
        allOf: []
      annotations:
        match:
          tag: ok
```
Deploy an app with image that is signed by the right privatekey but does not have the right annotation.

```
cosign sign --key cosign.key -a tag=notok docker.io/sangeetha/<image>:v6.0.0
```

```
acorn run -n mytes2 docker.io/sangeetha/<image>:v6.0.0
  ✗  ERROR:  App.api.acorn.io "mytes2" is invalid: spec.image: Invalid value: "docker.io/sangeetha/<image>:v6.0.0": disallowed by imageAllowRules: image docker.io/sangeetha/myfirstacorn:v6.0.0 is not allowed by rule testp1/testrules-project.signatures.0.anyOf
```

Error message presented to the user refers image not being allowed because of signature , when annotation match  was the one that failed.
