### ISSUE TITLE
Add CustomResourceDefinitions (CRDs) to acorn

### ISSUE THREAD

**Issue by cjellick** [acorn-io/acorn#329]
This has come up a few times in feedback from users.  We are investing different approaches to solving this.

Our challenge here is that because every CRD has its own unique impact and lifecycle, Acorn cannot reliably and predictably manage CustomResources generically.

We are kicking around different ideas, including bespoke support for different CRD-based systems (like various service meshes and ingresses) or a plugin framework.

If you have a specific CRD usecase, please share it here!

**Comment by denist-huma** [comment]
# Propose a new Acornfile syntax for Custom Resources

## Use case

We are in R&D team describe resources for our workloads in Kubernetes with CRDs.
The resources currently are the AWS S3 bucket, Redis and MongoDBUser (db + user pair) in-cluster provided by KubeDB.
There are several CRs we use with our operators at huma.com.

```yaml
apiVersion: db.operator.huma.com/v1alpha1
kind: MongoDBUser
metadata:
  name: ppserver-2513-db
spec:
  clusterRef:
    name: pr-preview-mongodb-cluster-2
    namespace: kubedb
  dataLifecycle: delete
  databaseName: ppserver-2513-db
  provider: kubedb
  roleName: readWrite
---
apiVersion: redis.operator.huma.com/v1alpha1
kind: RedisClaim
metadata:
  name: ppserver-rc
spec:
  haEnabled: false
  redisVersion: 6.2.5
  storage: 1Gi
---
apiVersion: storage.huma.com/v1alpha1
kind: S3Bucket
metadata:
  name: ppserver-2513-bucket
spec:
  region: eu-west-2
```

## Custom Resources syntax proposal

Used a [Authoring Acornfiles guide](https://docs.acorn.io/authoring/overview)

```cue
cr: {
    "db": {
        name: "ppserver-2513-db",
        apiVersion: "db.operator.huma.com/v1alpha1",
        kind: "MongoDBUser",
        spec: {
            "clusterRef": {
                "name": "pr-preview-mongodb-cluster-2",
                "namespace": "kubedb",
            },                
            "dataLifecycle": "delete",
            "databaseName": "ppserver-2513-db",
            "provider": "kubedb",
            "roleName": "readWrite",                
        },
    },
}
```

1. Custom Resources contained in an object to allow to reference their fields later like "cr.db.name".
1. There could be 2 Custom Resources with same name but different apiVersion/Kind, so such objects need a name field.
1. I see name, apiVersion, kind, spec present in all my Custom Resources. Only but spec can be empty. For example, an empty spec in my S3Bucket would create an S3 bucket in the default "us-east-1" region.

```cue
cr: {
    "bucket": {
        name: "ppserver-2513-bucket",
        apiVersion: "storage.huma.com/v1alpha1",
        kind: "S3Bucket",
        spec: {},
    },
}
```

**Comment by denist-huma** [comment]
## Watching for Custom Resources Status

Acorn can watch events with Custom Resources waiting for them to become "Ready".
Upon CR reaching the "Ready" phase, dependent container can be deployed.
Than give an opportunity to declare in a container `dependsOn: [ "cr.bucket", "cr.db", "cr.redis"]`.

Custom Resources in general have some fields inside their Status that represent a state when it is good to go.
The difference is in the field name and value, because there is up to CRD designer.

- apiVersion "kubedb.com/v1alpha2", kind "Redis", has ".status.phase: Ready"
- my "RedisClaim" has ".status.status: Ready"
- my "MongoDBUser" has ".status.status: Available"

## RBAC

Acorn need viewer ClusterRole for each Custom Resources, example:

```yaml
# permissions for end users to view mongodbusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodbuser-viewer-role
rules:
- apiGroups:
  - db.operator.huma.com
  resources:
  - mongodbusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.operator.huma.com
  resources:
  - mongodbusers/status
  verbs:
  - get
```
