### ISSUE TITLE
Server Side Apply Does Not Work

### ISSUE THREAD

**Issue by ekristen** [acorn-io/acorn#441]
Server Side Apply of Kubernetes YAML generated by Acorn returns an error.

```
Error from server (NotFound): the server could not find the requested resource (patch apps.api.acorn.io fragrant-grass)
```

```yaml
apiVersion: api.acorn.io/v1
kind: App
metadata:
  name: fragrant-grass
  namespace: acorn
spec:
  image: ghcr.io/acorn-io/library/mariadb:v10.6.8-focal-acorn.1
  volumes:
    - class: ebs-ephemeral
      size: 5Gi
      target: mysql-data-0
```

```console
$ k apply --server-side -f mariadb.yaml                                                                                                                                                                                    
```
