### ISSUE TITLE
Feature request: Simplify pods security hardenings

### ISSUE THREAD

**Issue by olljanat** [acorn-io/acorn#457]
Because of history and unwillingness to implement needed breaking change Docker and Kubernetes still defaults to `root` user and not to mention other security hardening which with most of the modern application would be able to work just fine.

Based on my experience most of the applications works just fine with security context like this:
```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534
  seccompProfile:
    type: RuntimeDefault
```
which with they can run on namespace where `restricted` Pod Security Policy is enforced.

That why it would be nice to have just one setting which can be enabled for Acorn app which will add that security context to deployment and `pod-security.kubernetes.io/enforce: restricted` label to namespace which it creates.

---

In additionally I have noticed many apps also works even with `readOnlyRootFilesystem: true` as long tmpfs is mounted to `/tmp` meaning something like this on deployment yaml
```yaml
    volumeMounts:
    - name: tmpfs
      mountPath: /tmp
  volumes:
  - name: tmpfs
    emptyDir:
      sizeLimit: 100Mi
```
and because it is recommended in [NSA: Kubernetes Hardening Guide](https://media.defense.gov/2021/Aug/03/2002820425/-1/-1/0/CTR_Kubernetes_Hardening_Guidance_1.1_20220315.PDF) it would be nice to have setting for it too.
