### ISSUE TITLE
Documentation error in TLS Certificates my-cert.yaml got invalid contents

### ISSUE THREAD

**Issue by denist-huma** [acorn-io/acorn#605]
```yaml
# my-cert.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-studio-cert
spec:
  dnsNames:
  - my-app.example.com
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: prod-issuer
    secretName: my-app-tls-secret
```
$ k apply -f domain-certificate.yaml
error: error parsing domain-certificate.yaml: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context
