### ISSUE TITLE
acorn install fail on AKS

### ISSUE THREAD

**Issue by meldafrawi** [acorn-io/acorn#670]
Steps to reproduce:

1. Create AKS cluster
2. install acorn
3. run `acorn check`

logs:
```
NAME                  PASSED    MESSAGE
RBAC                  true      User can create namespaces
NodesReady            true      All nodes are ready
DefaultStorageClass   true      Found default storage class default
IngressCapability     false     Ingress not ready (test timed out)
Exec                  true      Successfully executed command in container replica
Error: 1 checks failed
```

**Comment by meldafrawi** [comment]
Was able to bass the checks by deploying nginx ingress controller to **the default namespace**

if nginx ingress deployed to different namespace, the issue still exists.

1. `helm repo add nginx-stable https://helm.nginx.com/stable`
2. `helm repo update`
3. `helm install --set 'controller.setAsDefaultIngress=true' --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz nginx-ingress nginx-stable/nginx-ingress`
4. `acorn install --ingress-class-name nginx`

logs:
```
  ✔  Running Pre-install Checks                                                                                                                                                                                    
  ✔  Installing ClusterRoles                                                                                                                                                                                       
  ✔  Installing APIServer and Controller (image ghcr.io/acorn-io/acorn:v0.2.0)                                                                                                                                     
  ✔  Waiting for controller deployment to be available                                                                                                                                                             
  ✔  Waiting for API server deployment to be available                                                                                                                                                             
  ✔  Installation done                 
```

However when trying to run the following Acornfile:

```
containers: {
	app: {
		image: "redis:alpine"
	}
}
```
acorn was not able to download the image from the registry.
`acorn apps`

output:
```
NAME            IMAGE          HEALTHY   UP-TO-DATE   CREATED   ENDPOINTS   MESSAGE
hidden-sunset   73399bb43852   0/1       1            19s ago               [containers: app ImagePullBackOff: Back-off pulling image "127.0.0.1:30879/acorn/acorn@sha256:438b33ad07ea40f5c8cbbbc893b0faa2ed204dafac880c73ae6359b8f20ce17a"; hidden-sunset is not ready]

```

**Comment by cjellick** [comment]
@iwilltry42 thoughts on this? The fact that it only works if installed in the default namespace is odd.

@meldafrawi what version of k8s is this?

**Comment by meldafrawi** [comment]
k8s version: 1.24.3

**Comment by iwilltry42** [comment]
Hi @meldafrawi , in my tests, the ingresscapability check tends to timeout fairly often, since ingress-nginx seems to be fairly slow to populate the ingress address field.
That's why my PR over here increases the timeout to 1 minute.

This still seems odd. Can you verify that it works in general by creating any Ingress object while nginx is deployed in another namespace?
What we're looking for is that the `ADDRESS` field is populated and you can check that just with `kubectl get ingress myingress`.
It may take a while.

Here's a simple example for testing:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.local.on-acorn.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: myapp
            port: 
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

```
