### ISSUE TITLE
Containers don't consume Acorn image, but plain container image

### ISSUE THREAD

**Issue by josedev-union** [acorn-io/acorn#713]
This issue appeared in the following cases.
- When running the Acorn app from its local Directory, the initial replicas all consume the correct Acorn image. Once it is scaled out, new containers consume the plain container image.
- When running the Acorn app from an image, only the first container consumes the Acorn image and others don't from the initial deployment.

**Comment by cjellick** [comment]
Can you provide some yaml output of the k8s resources in question to illustrate what you mean?

**Comment by cjellick** [comment]
Hi again. Is there a difference between this issue and the other one you opened: https://github.com/acorn-io/acorn/issues/704?

**Comment by josedev-union** [comment]
> Hi again. Is there a difference between this issue and the other one you opened: #704?
Those are same, sorry, i forgot i did open already.

**Comment by josedev-union** [comment]
This is the pod spec of the replica created at initial app deployment.
```
    spec:
      containers:
      - args:
        - /acorn/scripts/start.sh
        image: 127.0.0.1:30484/acorn/acorn@sha256:ae591017c90b7afd90b8f4261250f3778ce91f60c4349f59480fe666695a8e19
        imagePullPolicy: IfNotPresent
        name: mongodb-3
      imagePullSecrets:
      - name: mongodb-0-pull-d27dc58d-fd5
```
This is the pod spec of the replica scaled out.
```
    spec:
      containers:
      - args:
        - /acorn/scripts/start.sh
        image: mongo:5.0.12
        imagePullPolicy: IfNotPresent
        name: mongodb-3
      imagePullSecrets:
      - name: mongodb-3-pull-d27dc58d-fd5
```
