### ISSUE TITLE
ingress on k3s not full working

### ISSUE THREAD

**Issue by eslizn** [acorn-io/acorn#945]
i use k3s to deploy acorn and encounter the following problems：

- IngressCapability     false     Ingress not ready (test timed out after 1 minute)
- app endpoint：http://[Pending Ingress] => default:80
- ssl error：TRAEFIK DEFAULT CERT

k3s install scripts：
```
curl -sfL https://get.k3s.io | sh -s - \
  --disable traefik \
  --disable servicelb \
  --advertise-address [server ip] \
  --disable-cloud-controller \
  --cluster-init \
  --cluster-domain=[mydomain]
```

traefik install
```
helm repo add traefik https://helm.traefik.io/traefik
helm repo update
helm install -n kube-system traefik traefik/traefik
kubectl patch svc traefik -n kube-system -p '{"spec": {"type": "ClusterIP", "externalIPs":["server ip"]}}'
```

acorn info：
```
client:
  version:
    commit: 1970d72e4c7bed86c118c7ae6cf49edba896c42f
    tag: v0.4.1-rc3
namespace:
  publicKeys:
  - keyID: ******
server:
  apiServerImage: ghcr.io/acorn-io/acorn:v0.4.1-rc3
  config:
    acornDNS: disabled
    acornDNSEndpoint: https://alpha-dns.acrn.io/v1
    autoUpgradeInterval: 5m
    clusterDomains:
    - .******
    defaultPublishMode: defined
    ingressClassName: traefik
    internalClusterDomain: svc.cluster.local
    letsEncrypt: enabled
    letsEncryptEmail: ******
    letsEncryptTOSAgree: true
    podSecurityEnforceProfile: baseline
    setPodSecurityEnforceProfile: true
  controllerImage: ghcr.io/acorn-io/acorn:v0.4.1-rc3
  dirty: false
  gitCommit: 1970d72e4c7bed86c118c7ae6cf49edba896c42f
  letsEncryptCertificate: enabled, pending (secrets "acorn-tls" not found)
  tag: v0.4.1-rc3
  userConfig:
    acornDNS: disabled
    acornDNSEndpoint: null
    autoUpgradeInterval: null
    clusterDomains:
    - .******
    defaultPublishMode: ""
    ingressClassName: traefik
    internalClusterDomain: ""
    letsEncrypt: enabled
    letsEncryptEmail: ******
    letsEncryptTOSAgree: true
    podSecurityEnforceProfile: ""
    setPodSecurityEnforceProfile: null
  version: v0.4.1-rc3+1970d72e
```
